### ISSUE TITLE
Support for react-native -.47 createJSModules calls

### ISSUE THREAD

**Issue by rohitgoyal** [gijoehosaphat/react-native-keep-screen-on#5]
Please update the library to support react-native 0.47
Following is the build failure error because of deprecated override method.  

> node_modules/react-native-keep-screen-on/android/src/main/java/com/gijoehosaphat/keepscreenon/KeepScreenOnPackage.java:26: error: method does not override or implement a method from a supertype
>     @Override
>     ^
> 1 error
> :react-native-keep-screen-on:compileReleaseJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-keep-screen-on:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.

**Comment by gijoehosaphat** [comment]
Done!
